[package]
name = "shared-buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
array-init="2.1.0"
smallvec = "1.13.2"
itertools = { version = "0.14.0",optional = true }
arbitrary = { version = "1.4.1",optional = true,features = ["derive"] }

[features]
test=["itertools","arbitrary"]
